name: PR Checks

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Cache hatch environment
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/hatch
          ~/.local/share/hatch
        key: ${{ runner.os }}-hatch-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-hatch-
        
    - name: Install hatch
      run: pip install hatch
      
    - name: Run quality checks
      run: hatch run check
      
    - name: Report status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ All quality checks passed!"
        else
          echo "❌ Quality checks failed. Please fix the issues and push again."
          exit 1
        fi
